---
name: build java application
on:
 push:
  branches:
   - master
jobs:
 buildjob:
  runs-on: Ubuntu-latest
  steps:
   - name: Clone the repo
     uses: actions/checkout@v4
   - name: Install java 17
     uses: actions/setup-java@v4
     with:
      java-version: '17'
      distribution: 'temurin'
      cache: maven
   - name: build the java code
     run: mvn clean install package
     
